# Generated by Django 4.2.14 on 2024-08-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='drucker',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='laptop',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='mini_pc',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='monitore',
            field=models.BooleanField(),
        ),
    ]
