# Generated by Django 4.2.14 on 2024-08-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_hardware_drucker_alter_hardware_laptop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='drucker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='laptop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='mini_pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='monitore',
            field=models.BooleanField(default=False),
        ),
    ]
